- ID: C-1
  bin_load_addr: '0x0'
  name: syn-sample-01
- ID: C-2
  bin_load_addr: '0x0'
  name: syn-sample-02
- ID: C-3
  bin_load_addr: '0x0'
  name: syn-sample-03
- ID: C-4
  bin_load_addr: '0x0'
  name: syn-sample-04
- ID: C-5
  bin_load_addr: '0x0'
  name: syn-sample-05
- ID: C-6
  bin_load_addr: '0x8000000'
  name: syn-sample-06
- ID: C-7
  bin_load_addr: '0x8000000'
  name: syn-sample-07
- ID: C-8
  bin_load_addr: '0x8000000'
  name: syn-sample-09
- ID: C-9
  bin_load_addr: '0x0'
  name: syn-sample-10
- ID: C-10
  bin_load_addr: '0x8000000'
  name: p2im-11
- ID: C-11
  bin_load_addr: '0x8000000'
  name: p2im-12
- ID: C-12
  bin_load_addr: '0x8000000'
  name: p2im-16
- ID: C-13
  bin_load_addr: '0x8000000'
  name: p2im-17
- ID: C-14
  bin_load_addr: '0x8000000'
  name: p2im-20
- ID: C-15
  bin_load_addr: '0x8000000'
  name: p2im-21
- ID: C-16
  bin_load_addr: '0x8000000'
  name: p2im-22
- ID: C-17
  bin_load_addr: '0x8000000'
  name: p2im-23
- ID: C-18
  bin_load_addr: '0x8000000'
  name: p2im-24
- ID: C-19
  bin_load_addr: '0x8000000'
  name: p2im-25
- ID: C-20
  bin_load_addr: '0x800c080'
  name: uemu-27
- ID: C-21
  bin_load_addr: '0x0'
  name: uemu-28
- ID: C-22
  bin_load_addr: '0x0'
  name: uemu-29
- ID: C-23
  bin_load_addr: '0x0'
  name: uemu-36
- ID: C-24
  bin_load_addr: '0x0'
  name: uemu-37
- ID: C-25
  bin_load_addr: '0x0'
  name: uemu-38
- ID: C-26
  bin_load_addr: '0x8000000'
  name: uemu-39
- ID: C-27
  bin_load_addr: '0x800c080'
  name: uemu-40
- ID: C-28
  bin_load_addr: '0x800c080'
  name: uemu-41
- ID: C-29
  bin_load_addr: '0x8000000'
  name: uemu-43
- ID: C-30
  bin_load_addr: '0x8000000'
  name: uemu-44
- ID: C-31
  bin_load_addr: '0x800c080'
  name: uemu-45
- ID: C-32
  bin_load_addr: '0x400000'
  name: zephyr-46
- ID: C-33
  bin_load_addr: '0x8000000'
  name: zephyr-47
- ID: C-34
  bin_load_addr: '0x8000000'
  name: zephyr-48
- ID: C-35
  bin_load_addr: '0x400000'
  name: zephyr-52
- ID: C-36
  bin_load_addr: '0x400000'
  name: zephyr-53
- ID: C-37
  bin_load_addr: '0x0'
  name: zephyr-54
- ID: C-38
  bin_load_addr: '0x400000'
  name: zephyr-55
- ID: C-39
  bin_load_addr: '0x202000'
  name: contiki-ng-58
- ID: C-40
  bin_load_addr: '0x202000'
  name: contiki-ng-59
- ID: C-41
  bin_load_addr: '0x202000'
  name: contiki-ng-60
